title: Connor York
description: My Personal Blog
author: Connor York
logo: /static/img/avatar.png
github: https://github.com/connoryork
about: Software Engineer

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: connoryork
# google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
